### ISSUE TITLE
AC-IN clamp labled wrong

### ISSUE THREAD

**Issue by frfrh** [voltlog/Valve-Actuator#1]
It looks like the Labels on the AC-IN clamp are reversed, so the one which should be labled `N` actually has the lable `L` which mean even when blowing the fuses all the board will still have full live on everything which is supposed to be neutral which can be a huge safety issue.

![grafik](https://user-images.githubusercontent.com/93924020/140818727-5e1677ee-9535-4a19-a2f4-8afd98fa31a2.png)

**Comment by voltlog** [comment]
Thanks for reporting this issue. There is now a mention of this in the README and I will address the issue in the next revision.
