### ISSUE TITLE
GPIO pins

### ISSUE THREAD

**Issue by ClausMunch** [voltlog/Valve-Actuator#3]
Could you describe what GPIO to use for the GPIO pins on the board? 
I think I have traced it back to GPIO 21 (SDA) and GPIO 22 (SCL), but I'm not having much luck turning on a small OLED on this (also tested it with a generic ESP32, where it works)

**Comment by ClausMunch** [comment]
What I acutally wanted to do, was to have a small OLED through the housing, able to cycle through some basic info (IP, valve status, temperature), with the ability to toggle the display on and off with the onboard button.
Maybe add a temperature sensor on the one wire, to be able to monitor the temperature in the utility space.

Hope it makes sense :)

**Comment by voltlog** [comment]
I2C pins are IO21/SDA and IO22/SCL with more information regarding GPIO available in the PDF schematic included in this repo: https://github.com/voltlog/Valve-Actuator/blob/main/Schematic_revC.pdf

I am also going to update the quick start guide to include information about this as I guess most people look there first.

I am going to close this issue now.
