### ISSUE TITLE
[QUESTION] Is possible connected with HVAC?

### ISSUE THREAD

**Issue by limkinZero** [voltlog/Valve-Actuator#4]
Hi,

I'm looking for something to allow me control my valvules of floor heating.  Currently, I've a board (Möhlenhoff Alpha-Basis) where the actuators and thermostats are connected. Also, there is an output to connect with my HVAC machine for it to activate the water pump. Is it possible somehow to connect it to the voltlog board?

**Comment by voltlog** [comment]
Hi,
This is not an issue with the current published design.

Please note that this design is for advanced users and whether or not extra functionality can be obtained by interconnecting with other systems is something you will have to figure out on your own.

**Comment by brainstormi** [comment]
Hi @voltlog...
   Could you confirm how to send the signal to the pump to power on taking into account this works as a dry contact... ? Taking a look at the board I'm not sure how this would be done
