### ISSUE TITLE
Problems with version 2024.6.1 Jun 21 2024

### ISSUE THREAD

**Issue by rodrigonogueras** [voltlog/Valve-Actuator#6]
Hello,

I use your Valve-Actuator for more than a year. I usually upgrade the firmware when ESPHome release a new version. I did not have any problem during all this time.

Since I upgraded to 2024.6.1 Jun 21 2024 it ask me to make some changes. https://esphome.io/changelog/2024.6.0.html
OTA Platforms and 1-Wire

Since this change I see lots of Reset Reason = "Timer Group 1 Watch Dog Reset Digital Core" or "Software Reset CPU" and the valves are not working well because it loose the connectivity.

![image](https://github.com/voltlog/Valve-Actuator/assets/78388686/aeb7fd8d-de13-4d48-b3b8-5bab7924bf97)

I don't know if you can help with this problem.

This is the actual code of one of them:
###########################
esphome:
  name: voltlog-p-1
  friendly_name: voltlog-p-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Voltlog-P-1 Fallback Hotspot"
    password: "xxxxxxxxxxxxxxxx"

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.142
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

captive_portal:

#MQTT
mqtt:
  broker: !secret mqtt_host
  port: 1883
  topic_prefix: sensores/voltlog/voltlog-p-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  log_topic:
    topic: debug
    level: none

switch:
  - platform: gpio
    pin: 23
    name: Valvula 01
  - platform: gpio
    pin: 19
    name: Valvula 02
  - platform: gpio
    pin: 18
    name: Valvula 03
  - platform: gpio
    pin: 15
    name: Valvula 04
  - platform: gpio
    pin: 13
    name: Valvula 05
  - platform: gpio
    pin: 14
    name: Valvula 06
  - platform: gpio
    pin: 27
    name: Valvula 07
  - platform: gpio
    pin: 26
    name: Valvula 08
  - platform: gpio
    pin: 25
    name: Valvula 09
  - platform: gpio
    pin: 32
    name: Valvula 10

one_wire:
  - platform: gpio
    pin: GPIO4
#    update_interval: 5s

sensor:
  - platform: dallas_temp
    address: 0xe60922549523b021
    name: P-1 Temp impulsion
    update_interval: 5s

  - platform: dallas_temp
    address: 0xe80822546f73c121
    name: P-1 Temp retorno
    update_interval: 5s
  
# substitutions
substitutions:
  devicename: "voltlog-p-1"
  friendlyname: "voltlog-p-1"

packages:
  text-sensor: !include diag/diag-text-sensor.yaml 
  switch: !include diag/diag-switch.yaml
  sensor: !include diag/diag-sensor.yaml  
  
debug:
  update_interval: 5s       
  
###########################  

Thanks for your help.

**Comment by voltlog** [comment]
Unfortunately I can't help with this because according to your findings it is not a hw problem but something to do with the firmware. I would say revert back to a previous known working version of firmware and don't upgrade. 

You could also try to get help by going to ESPHome Discord/Github and post the issue there.

Personally I never upgrade my devices for no good reason, if it works, it doesn't need an update.

**Comment by rodrigonogueras** [comment]
OK, Thanks.
